Start preparing for TypeJointMatrixINTEL switch
KhronosGroup/SPIRV-LLVM-Translator pull request #1935
Opened 2023-03-31 12:25 UTC by MrSidims

The patch adds TypeJointMatrixINTELv2 which maps to new type OpCode
6184. Under new OpCode matrix type no longer has Layout parameter. The patch also moved 'scope' to optional matrix muladd instruction.

The changes are done only in the consumer part to prepare the switch and make E2E switch backward compatible by preparing consumers ahead of time.

Unfortunately there is no way to add a test foe this unless it's binary test, but it seems to be a bit unsafe to add this, so the patch was tested localy.

Spec change:
https://github.com/intel/llvm/pull/8175

2023-03-31 12:25 UTC, MrSidims commented
@asudarsa @maksimsab @jgstarIntel please take a look

2023-04-03 12:10 UTC, maksimsab requested changes
I see in the patch description that `scope is moved to optional matrix muladd instruction`.

Could you please clarify where is it done? Unfortunately, not obvious for me :(

2023-04-03 12:10 UTC, maksimsab commented on lib/SPIRV/libSPIRV/SPIRVType.h
> +  SPIRVValue *getScope() const {
Could you please separate this methods by blank lines?

2023-04-03 12:15 UTC, MrSidims commented on lib/SPIRV/libSPIRV/SPIRVInstruction.h
> +_SPIRV_OP(JointMatrixUUMad, true, 6, true)
@maksimsab move of scope parameter happens here (see the second 'true').

Note, that 'scope' according to old spec is mandatory parameter and per new spec is removed at all. So to balance it here making both representations translatable we have to add is as optional for a while.

2023-04-03 13:06 UTC, MrSidims commented on lib/SPIRV/libSPIRV/SPIRVType.cpp
> +                TheId), CompType(CompType), Args(Args) {}
Thanks! We probably should also scan other places in the translator to embrace this optimization

2023-04-04 11:29 UTC, maksimsab approved these changes
LGTM! Thank you

2023-04-04 14:26 UTC, merged