[DebugInfo] Translate DW_OP_LLVM_arg with more then one parameter
KhronosGroup/SPIRV-LLVM-Translator pull request #1987
Opened 2023-05-02 16:07 UTC by MrSidims

DebugOperation is updated adding (in a scope of NonSemantic.Shader.DebugInfo.200):
If Operation is Arg, the DebugOperation has only
one optional operand, which is <id> of a non-debug instruction whose value is used as an argument of a debug expression.

2023-05-02 16:07 UTC, MrSidims commented
@vmaksimo @asudarsa @maksimsab @jgstarIntel @LU-JOHN please take a look

2023-05-03 14:38 UTC, maksimsab approved these changes
LGTM

2023-05-03 14:39 UTC, maksimsab requested changes
Are your changes related to the failed test?

2023-05-03 14:46 UTC, vmaksimo commented
@MrSidims  Sure, I'll take a look

2023-05-04 08:56 UTC, maksimsab approved these changes
LGTM

2023-05-04 13:03 UTC, vmaksimo approved these changes

2023-05-04 13:13 UTC, merged