Translate LLVM-IR zero-length arrays to 1-length arrays in SPIR-V
KhronosGroup/SPIRV-LLVM-Translator pull request #2743
Opened 2024-10-07 14:26 UTC by lbushi25

The LLVM-IR type of zero-length array does not seem to have a mapping into SPIR-V type, rather it outputs an error since the obvious choice of zero-length array is not valid in SPIR-V. This, for example, prohibits us from using unbounded arrays in SYCL device kernels. This PR attempts to introduce a workaround to this by lowering a zero-length array in LLVM-IR to a 1-length array in SPIRV.

2024-10-07 14:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-LLVM-Translator?pullRequest=2743) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-LLVM-Translator?pullRequest=2743) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-LLVM-Translator?pullRequest=2743) it.</sub>

2024-10-07 16:22 UTC, lbushi25 commented on lib/SPIRV/SPIRVWriter.cpp
Only line 452-469 have functional changes in this file. The rest are formatter artifacts.

2024-10-07 16:26 UTC, svenvh requested changes
Unconditionally generating non-conformant SPIR-V seems not right.  The suggestion in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/417 was to hide such functionality behind an option (or perhaps we should consider a SPIR-V extension?).

2024-10-07 16:33 UTC, lbushi25 commented
> Unconditionally generating non-conformant SPIR-V seems not right. The suggestion in #417 was to hide such functionality behind an option (or perhaps we should consider a SPIR-V extension?).

Why would this be non-conformant SPIR-V?
I'm not generating arrays of size zero. I'm instead modifying the lowering of LLVM IR arrays of zero-length to SPIR-V arrays of length 1 which are, at least to the best of my knowledge, valid in SPIR-V

2024-10-08 07:36 UTC, svenvh commented
> Why would this be non-conformant SPIR-V? I'm not generating arrays of size zero. I'm instead modifying the lowering of LLVM IR arrays of zero-length to SPIR-V arrays of length 1 which are, at least to the best of my knowledge, valid in SPIR-V.

My apologies, I completely misread your initial description.  Lowering to a SPIR-V array of length 1 is of course completely conformant.

2024-10-08 08:19 UTC, svenvh commented on lib/SPIRV/SPIRVWriter.cpp
Ideally we should leave out the formatter artifacts as they may complicate potential backports of this commit.  This repo ought to be clang-formatted, so we should fix the formatting in a separate PR; I can do so if you wish.

2024-10-08 14:07 UTC, lbushi25 commented on lib/SPIRV/SPIRVWriter.cpp
> Ideally we should leave out the formatter artifacts as they may complicate potential backports of this commit. This repo ought to be clang-formatted, so we should fix the formatting in a separate PR; I can do so if you wish.
> 
> Update: I've created #2744 . When that has landed, you can just rebase on top of `main` and the unrelated formatting changes should disappear from your patch.

Thanks for creating the formatting patch. I have merged it into my branch and also made the changes you suggested.

2024-10-08 14:13 UTC, svenvh approved these changes

2024-10-08 17:05 UTC, MrSidims approved these changes

2024-10-08 17:06 UTC, merged

2026-01-28 11:47 UTC, karolzwolak commented
/backport llvm_release_190

2026-01-28 13:25 UTC, karolzwolak commented
/backport llvm_release_180

2026-01-28 13:26 UTC, karolzwolak commented
/backport llvm_release_170

2026-01-28 13:26 UTC, karolzwolak commented
/backport llvm_release_160

2026-01-28 13:26 UTC, karolzwolak commented
/backport llvm_release_150

2026-01-28 13:26 UTC, karolzwolak commented
/backport llvm_release_140