Ignore experimental_noalias_scope_decl intrinsic
KhronosGroup/SPIRV-LLVM-Translator pull request #906
Opened 2021-02-04 16:12 UTC by MrSidims

Signed-off-by: Dmitry Sidorov <dmitry.sidorov@intel.com>

2021-02-04 17:05 UTC, AlexeySotkin approved these changes

2021-02-09 19:16 UTC, AlexeySachkov reviewed
It would be nice to have a LIT test for this change, I think

2021-02-12 14:10 UTC, AlexeySotkin requested changes
@MrSidims please add a test. Thanks.

2021-02-15 20:24 UTC, AlexeySachkov commented on test/experimental_noalias_scope_decl.ll
> +; RUN: llvm-as %s -o %t.bc
The filename should be `test/llvm-intrinsics/experimental.noalias.scope.decl.ll` to align with other such tests

2021-02-15 21:25 UTC, AlexeySachkov approved these changes

2021-02-15 21:26 UTC, merged